=== DalavanCloud/myfaces-tobago/core/src/main/resources/org/apache/myfaces/tobago/config/tobago-config_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

<!ENTITY % Boolean "(true|false|yes|no)">

<!ELEMENT tobago-config (theme-config, resource-dir*, load-theme-resources-from-classpath?, mapping-rule*, ajax-enabled?, renderers?)>

<!ELEMENT theme-config (default-theme, supported-theme*)>
<!ELEMENT default-theme (#PCDATA)>
<!ELEMENT supported-theme (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT display-name (#PCDATA)>
<!ELEMENT fallback (#PCDATA)>

<!ELEMENT resource-dir (#PCDATA)>

<!-- deprecated -->
<!ELEMENT load-theme-resources-from-classpath (#PCDATA)>

<!ELEMENT mapping-rule (request-uri, forward-uri, attribute*)>
<!ELEMENT request-uri (#PCDATA)>
<!ELEMENT forward-uri (#PCDATA)>

<!ELEMENT attribute (key, value)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT ajax-enabled (#PCDATA)>

<!ELEMENT renderers (renderer)*>
<!ELEMENT renderer (name|supported-markup)*>
<!ELEMENT supported-markup (markup)*>
<!ELEMENT markup (#PCDATA)>

=== DalavanCloud/myfaces-tobago/example/demo/webapp/WEB-INF/tobago-config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE tobago-config PUBLIC
    "-//Atanion GmbH//DTD Tobago Config 1.0//EN" "tobago-config_1_0.dtd">

<tobago-config>

  <theme-config>
    <default-theme>com.atanion.tobago.context.SpeysideTheme</default-theme>
    <supported-theme>com.atanion.tobago.context.ScarboroughTheme</supported-theme>
<!--    <supported-theme>com.atanion.tobago.context.TuiTheme</supported-theme>-->
    <supported-theme>com.atanion.tobago.context.InexsoTheme</supported-theme>
    <supported-theme>com.atanion.tobago.context.SapTheme</supported-theme>
<!--    <supported-theme>com.atanion.tobago.context.CharlottevilleTheme</supported-theme>-->
  </theme-config>

  <resource-dir>tobago-app</resource-dir>
  <resource-dir>tobago</resource-dir>

  <mapping-rule>
    <request-uri>/welcome.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/welcome.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/text.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/text.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/link.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/link.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/checkbox.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/checkbox.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/select.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/select.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/sheet.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/sheet.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/layout.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/layout.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/tab.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/tab.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/utils.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/utils.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/object.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/object.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/file.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/fileUpload.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/fileShow.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/fileShow.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/toolbar.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/toolbar.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/tree.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/tree.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/treeListbox.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/treeListbox.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/validation.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/validation.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/editor.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/editor.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/builder/index.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>builder/index.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/builder/enterPagename.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>builder/enterPagename.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/builder/viewSource.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>builder/viewSource.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/quiz.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>snip/quiz.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/tutorial.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>tutorial-folder/tutorial.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/banking.view</request-uri>
    <forward-uri>/demo.jsp</forward-uri>
    <attribute>
      <key>demoContent</key>
      <value>banking-folder/banking.jsp</value>
    </attribute>
  </mapping-rule>

  <mapping-rule>
    <request-uri>/screenshot.view</request-uri>
    <forward-uri>screenshot/screenshot.jsp</forward-uri>
    <attribute>
      <key>sceenshotContent</key>
      <value>screenshot/screenshot.jsp</value>
    </attribute>
  </mapping-rule>

</tobago-config>
